package com.avlino.tables.jobOrder.entity

case class JobOrderValue(containerId: String,
                         containerVisitId: String,
                         containerClass: String,
                         blockOfWork: String,
                         bayOfWork: String,
                         rowOfWork: Option[Int],
                         tierOfWork: Option[Int],
                         containerWeight: Double,
                         containerIso: String,
                         containerType: Option[String],
                         specialType: Option[String],
                         containerCommodity: Option[String],
                         actualContainerSize: Option[String],
                         containerSize: Option[String],
                         countchejobs: Option[Int],
                         moveStage: String,
                         moveType: String,
                         portOfDischargeKey: Option[String],
                         vesselArrivalDate: Option[String],
                         vesselArrivalTime:Option[String],
                         vesselDepartureDate:Option[String],
                         vesselDepartureTime:Option[String],
                         vesselBerthNumber:Option[String]
)
